

ERROR_CODE(BUFFERING_FAILED, -1),
ERROR_CODE(BUFFERING_SUCCESS, 0),
ERROR_CODE(BUFFERING_INVALIDARGS, 1),
ERROR_CODE(BUFALLOCATOR_LOCK_ERR, 2),
ERROR_CODE(BUFALLOCATOR_INVALIDARGS, 3),
ERROR_CODE(BUFALLOCATOR_SUCCESS, 4),
ERROR_CODE(BUFALLOCATOR_FREEBUF_ERR, 5),
ERROR_CODE(BUFALLOCATOR_NOTFOUND, 6),
ERROR_CODE(BUFALLOCATOR_BAD_ALLOC, 7),
ERROR_CODE(__END_OF_ERRLIST, INT_MAX)
